# Generated by Django 4.1.5 on 2023-01-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('elem', 'elementary'), ('pre', 'pre-intermediate'), ('inter', 'intermediate'), ('upper', 'upper-intermediate'), ('adv', 'advanced')], default='elem', max_length=50),
        ),
    ]
