# Generated by Django 4.1.5 on 2023-01-28 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='studen_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='user',
            name='teacher',
        ),
        migrations.AddField(
            model_name='user',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='teacher_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
