# Generated by Django 4.1.5 on 2023-01-06 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_work', models.CharField(choices=[('HW', 'homework'), ('CW', 'classwork')], max_length=30)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_room', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_answer', models.CharField(max_length=150)),
                ('flag', models.IntegerField(default=0)),
                ('accepted', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_answer', to='rooms.answers')),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='task_lesson', to='rooms.lessons')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='room_lesson', to='rooms.room')),
            ],
        ),
    ]
