# Generated by Django 4.1.5 on 2023-01-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essa',
            name='teacher_text',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
