# Generated by Django 4.1.5 on 2023-01-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='answer',
        ),
        migrations.AddField(
            model_name='answers',
            name='tasks',
            field=models.ManyToManyField(related_name='task_answer', to='rooms.tasks'),
        ),
    ]
