# Generated by Django 4.1.5 on 2023-01-28 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0002_remove_essa_user_essa_student_essa_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essa',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_essays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='essa',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
