# Generated by Django 4.1.5 on 2023-01-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_teacher_user_is_teacher_remove_user_student_and_more'),
        ('rooms', '0002_alter_essa_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essa',
            name='user',
        ),
        migrations.AddField(
            model_name='essa',
            name='students',
            field=models.ManyToManyField(related_name='essays', to='account.student', verbose_name='essa'),
        ),
    ]
