# Generated by Django 4.1.5 on 2023-01-09 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_tasks_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='rooms',
        ),
    ]
