# Generated by Django 4.1.5 on 2023-02-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_essa_teacher_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='ff',
        ),
        migrations.AddField(
            model_name='essa',
            name='deadline',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
