# Generated by Django 4.1.5 on 2023-01-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_remove_tasks_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='count_lessons',
            field=models.IntegerField(default=0),
        ),
    ]
