# Generated by Django 4.1.5 on 2023-01-24 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0003_remove_essa_user_essa_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='essa',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='essays', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
