# Generated by Django 4.1.5 on 2023-01-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_answers_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='accepted',
        ),
        migrations.AddField(
            model_name='answers',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
