# Generated by Django 4.1.5 on 2023-01-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_count_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='payment',
            field=models.IntegerField(default=0),
        ),
    ]
