# Generated by Django 4.1.5 on 2023-01-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_essa'),
    ]

    operations = [
        migrations.AddField(
            model_name='essa',
            name='text',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='essa',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
