# Generated by Django 4.1.5 on 2023-01-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_room_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='room',
        ),
        migrations.AddField(
            model_name='lessons',
            name='level',
            field=models.CharField(choices=[('elem', 'elementary'), ('pre', 'pre-intermediate'), ('inter', 'intermediate'), ('upper', 'upper-intermediate'), ('adv', 'advanced')], default='elem', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='lessons',
            field=models.ManyToManyField(related_name='room_lesson', to='rooms.lessons'),
        ),
        migrations.AddField(
            model_name='room',
            name='level',
            field=models.CharField(choices=[('elem', 'elementary'), ('pre', 'pre-intermediate'), ('inter', 'intermediate'), ('upper', 'upper-intermediate'), ('adv', 'advanced')], default='elem', max_length=50),
        ),
    ]
