# Generated by Django 4.1.5 on 2023-01-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_remove_tasks_room_lessons_level_room_lessons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='level',
        ),
        migrations.AlterField(
            model_name='room',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='room_lesson', to='rooms.lessons'),
        ),
    ]
