# Generated by Django 4.1.5 on 2023-01-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_remove_room_level_alter_room_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='level',
            field=models.CharField(choices=[('elem', 'elementary'), ('pre', 'pre-intermediate'), ('inter', 'intermediate'), ('upper', 'upper-intermediate'), ('adv', 'advanced')], default='elem', max_length=50),
        ),
    ]
