# Generated by Django 4.1.5 on 2023-01-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_room_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
