# Generated by Django 3.2.9 on 2023-02-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
