# Generated by Django 3.2.9 on 2023-02-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_table_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
